-- 4260 Renner Manual
-- 4529 LOJAS RENNER MANUAL
DECLARE @DT AS DATE = '2025-10-07' -- PRIMEIRO DIA DESEJADO
DECLARE @SQL NVARCHAR(MAX);
DECLARE @TableName AS VARCHAR(50) = 'totalinfo_' + FORMAT(@DT, 'yyyy_MM');

IF OBJECT_ID('tempdb..#NOMES_PH') IS NULL
BEGIN
    CREATE TABLE #NOMES_PH (
        NOME VARCHAR(255)
    );
    -- Insere os nomes específicos na tabela temporária
    INSERT INTO #NOMES_PH (NOME) VALUES 
        ('MAURICIO KLOSTERMANNE SALES'),
        ('WENDY KAUANA DOS SANTOS PEREIRA'),
        ('JESSICA MARIA VILAS BOAS DE OLIVEIRA'),
        ('RAMON NUNES MOREIRA'),
        ('LUCAS MURILO PROCKSCH DA CRUZ'),
        ('LARYSSA VITORIA SILVA DA ROCHA'),
        ('LEONARDO NEVES ORTEGA'),
        ('BRUNO CURUCA LOURENÇO'),
        ('NERIANE CRISTINA GARCIA'),
        ('CINTIA ADAO MENDES'),
        ('APARECIDA CRISTIANE DE OLIVEIRA'),
        ('JOYCE JESUS DA SILVA');	
END;

IF OBJECT_ID ('TEMPDB..##DISCAGENS_TWO') IS NOT NULL DROP TABLE ##DISCAGENS_TWO

-- Monta a query dinâmica para ##DISCAGENS_TWO
SET @SQL = '
SELECT *
INTO ##DISCAGENS_TWO
FROM OPENQUERY (EXPERT,''
	SELECT 
		A.GrupoPrincipal AS ID_FILA,
		A.Agente AS USUARIO,
		SUM(CASE WHEN A.OrigemChamada = ''''entrante'''' THEN 1 ELSE 0 END) AS RECEPTIVO,
		SUM(CASE WHEN A.OrigemChamada <> ''''entrante'''' THEN 1 ELSE 0 END) AS ATIVO,
		COUNT(*) AS TOTAL
	FROM ' + @TableName + ' a
	WHERE DATE(a.instante) = ''''' + FORMAT(@DT, 'yyyy-MM-dd') + '''''
	AND a.GrupoPrincipal IN (
		''''4522'''',	-- LOJAS RENNER ATÉ 720 DIAS
		''''4525''''    -- LOJAS RENNER ACIMA DE 721 DIAS - FILA WO
		)
	GROUP BY 
		A.GrupoPrincipal,
		A.Agente
'')
'

EXEC sp_executesql @SQL

SET @SQL = '
SELECT  
	''TRCWO'' AS COD_ASSESSORIA, 
	FORMAT(E.DATA, ''yyyyMM'') AS PERIODO, 
	FORMAT(E.DATA, ''dd/MM/yyyy'')+'' ''+CAST(E.HORA_LOGIN AS VARCHAR(8)) AS PRIMEIRO_LOGIN,
	FORMAT(E.DATA, ''dd/MM/yyyy'')+'' ''+CAST(E.HORA_LOGOUT AS VARCHAR(8)) AS ULTIMO_LOGOUT,
	CASE
		WHEN ph.NOME IS NOT NULL THEN CONCAT(E.USUARIO, ''_ph'')
		ELSE E.USUARIO
	END AS USUARIO,
	''CLT'' AS REGIME,
	ISNULL(FORMAT(C.DTADMISSAO_RECUP, ''dd/MM/yyyy''), '''' ) AS DATA_ADMISSAO,
	''06:20:00'' AS CARGA_HORARIA,
	ISNULL(E.TEMPO_LOGADO, '''' ) AS TTL, 
	ISNULL(CONVERT(VARCHAR(8),
		DATEADD(SECOND, DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_LOGADO)
		- DATEDIFF(SECOND, ''00:00:00'', E.PAUSA)
		- DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_FALADO)
		- DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_TABULACAO)
	, ''00:00:00''), 108), '''' ) AS TTD,
	ISNULL(E.TTPNR, '''' ) AS TTPNR,
	ISNULL(E.TTPE, '''' ) AS TTPE,  
	ISNULL(E.TEMPO_TABULACAO, '''' ) AS TTT,  
	ISNULL(E.TEMPO_FALADO, '''' ) AS TTA,
	CONVERT(VARCHAR(8),
         DATEADD(SECOND, (DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_LOGADO)
                 - DATEDIFF(SECOND, ''00:00:00'', E.PAUSA)
                 - DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_FALADO)
                 - DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_TABULACAO))
         /COALESCE(NULLIF(E.N_ATENDIDAS,0),1), ''00:00:00''), 108) AS TMD,
	CONVERT(VARCHAR(8),
		DATEADD(SECOND, (DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_TABULACAO)
		/COALESCE(NULLIF(E.N_ATENDIDAS,0),1)), ''00:00:00''), 108) AS TMT,
	CONVERT(VARCHAR(8),
		DATEADD(SECOND, (DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_FALADO)
		/COALESCE(NULLIF(E.N_ATENDIDAS,0),1)), ''00:00:00''), 108) AS TMA,
	ISNULL(D.ATIVO,0) AS ATENDIDAS_ATIVO,
	ISNULL(D.RECEPTIVO,0) AS ATENDIDAS_RECEPTIVO
FROM  
OPENQUERY (expert, ''
	SELECT 
		a.dia AS DATA,
		a.agente AS USUARIO,
		a.nome AS NOME,
		a.login AS HORA_LOGIN,
		a.logout AS HORA_LOGOUT,
		a.logado AS TEMPO_LOGADO,
		a.tempo_pausa_hora AS PAUSA,
		p.TTPNR AS TTPNR,	
		TIMEDIFF(a.tempo_pausa_hora,COALESCE(p.TTPNR,0)) AS TTPE,
		a.pausas_hora AS N_PAUSAS,
		a.atendidas AS N_ATENDIDAS,
		a.tempo_falado_hora AS TEMPO_FALADO,
		a.tempo_off_dia AS TEMPO_OCIOSIDADE,
		a.tempo_tabulacao_hora AS TEMPO_TABULACAO
	FROM relatorio_agentes_hora a 
	LEFT JOIN (SELECT
		SEC_TO_TIME(SUM(TIME_TO_SEC(TIMEDIFF(DSC_FINAL, DSC_INICIO)))) AS TTPNR,
		DSC_AGENTE AS DSC_AGENTE,
		DATE(DAT_OCORRENCIA) AS DATA
		FROM tb_relatorio_pausa
		WHERE (DSC_PAUSA LIKE ''''%PAUSA%EXPERT%'''' OR DSC_PAUSA LIKE ''''%10%'''' OR DSC_PAUSA LIKE ''''%20%'''')
		GROUP BY DSC_AGENTE, DATE(DAT_OCORRENCIA)
		) p ON a.agente = p.dsc_agente AND a.dia = p.data
	WHERE 
		a.dia = ''''' + FORMAT(@DT, 'yyyy-MM-dd') + '''''
		AND a.grupoprincipal IN (''''4522'''') 
	'') E
LEFT JOIN CAD_RECUP C ON E.USUARIO = C.CODDISCA_RECUP COLLATE SQL_Latin1_General_CP1_CI_AS AND C.ULTGRUPO_RECUP = ''RENNER''
LEFT JOIN ##DISCAGENS_TWO D ON E.USUARIO = D.USUARIO
LEFT JOIN #NOMES_PH ph ON E.NOME  = ph.NOME
'
PRINT @SQL;
EXEC sp_executesql @SQL