USE SRC

SELECT TOP 100 * FROM CAD_ACO
SELECT TOP 100 * FROM [TRC-DC-BD2].PLANEJAMENTO.DBO.CARTEIRA WHERE DESCR_CAR LIKE '%YDUQS%'


-->>>>>>>>>>>> SMS
SELECT 
    --COUNT(*)
    TOP 100 * 
FROM [TRC-DC-BD2].PLANEJAMENTO.DBO.SMS 
WHERE CPF = '15566166784   ' 
AND CAST(DATA AS DATE) = '2026-01-12'

-->>>>>>>>>>>> RCS
SELECT 
    --COUNT(*)
    TOP 100 * 
FROM [TRC-DC-BD2].PLANEJAMENTO.DBO.RCS 
WHERE CPF = '15566166784   ' 
AND CAST(DATA AS DATE) = '2026-01-12'

-->>>>>>>>>>>> EMAIL
SELECT 
    --COUNT(*)
    TOP 100 * 
FROM [TRC-DC-BD2].PLANEJAMENTO.DBO.EMAIL 
--WHERE CPF = '15566166784   ' 
WHERE CAST(DATA AS DATE) = '2026-01-12'

-->>>>>>>>>>>> WHATS
SELECT 
    --COUNT(*)
    TOP 100 * 
FROM [TRC-DC-BD2].PLANEJAMENTO.DBO.WHATS 
--WHERE CPF = '15566166784   ' 
WHERE CAST(DATA AS DATE) = '2026-01-12'

SELECT 
    TOP 100 * 
FROM [TRC-DC-BD2].PLANEJAMENTO.DBO.MAILING_HIST WHERE COD_CLI = 252 AND DATA = '20260112'

SELECT
    cpf,
    COUNT(DISTINCT contrato) AS qtd_contratos
FROM [TRC-DC-BD2].PLANEJAMENTO.DBO.MAILING_HIST 
WHERE COD_CLI = 252 AND DATA = '20260112'
GROUP BY cpf
ORDER BY qtd_contratos DESC;


-- Separando por canal de disparo
-- E filtros de segmentação do produto
-- Estácio Ativo
-- - Separar por Renovação e Base Liquida
-- Estácio Inativo
-- Wyden Ativo
-- Wyden Inativo

SELECT
    M.DATA,
    M.CONTRATO,
    M.CPF,
    M.ATRASO,
    M.COD_CLI,
    Y.REGIONAL,
	Y.GRUPO,
	Y.SPD,
	Y.BU,
	Y.MODALIDE,
	Y.STDEBITO,
	Y.STALUNO,
	Y.CURSO,
	Y.APROACAD,
    Y.PRODUTO,
    Y.ULTRENOV,
    CASE
		WHEN ATRASO BETWEEN 1 AND 7		        THEN 'A - 01 - 07'
		WHEN ATRASO BETWEEN 8 AND 15		    THEN 'B - 08 - 15'
		WHEN ATRASO BETWEEN 16 AND 30		    THEN 'C - 16 - 30'
		WHEN ATRASO BETWEEN 31 AND 60		    THEN 'D - 31 - 60'
		WHEN ATRASO BETWEEN 61 AND 90		    THEN 'E - 61 - 90'
		WHEN ATRASO BETWEEN 91 AND 180	        THEN 'F - 91 - 180'
		WHEN ATRASO BETWEEN 181 AND 270		    THEN 'G - 181 - 270'
		WHEN ATRASO BETWEEN 271 AND 360		    THEN 'H - 271 - 360'
		WHEN ATRASO BETWEEN 361 AND 540		    THEN 'I - 361 - 540'
		WHEN ATRASO BETWEEN 541 AND 720		    THEN 'J - 541 - 720'
		WHEN ATRASO BETWEEN 721 AND 1080		THEN 'K - 721 - 1080'
		WHEN ATRASO BETWEEN 1081 AND 1440		THEN 'L - 1081 - 1440'
		WHEN ATRASO BETWEEN 1441 AND 1800		THEN 'M - 1441 - 1800'
		WHEN ATRASO > 1800                      THEN 'N - Maior 1800'
	ELSE '0 - Menor 8'
	END FX_ATRASO
INTO #BASE_YDUQS
FROM [TRC-DC-BD2].PLANEJAMENTO.DBO.MAILING_HIST M
LEFT JOIN (
	SELECT
		a.CONTRATO_FIN,
		MAX(CASE WHEN a.COD_INDICADOR = 'REGIONAL' THEN a.VL_INDICADOR ELSE NULL END) AS REGIONAL,
		MAX(CASE WHEN a.COD_INDICADOR = 'GRUPO' THEN a.VL_INDICADOR ELSE NULL END) AS GRUPO,
		MAX(CASE WHEN a.COD_INDICADOR = 'SPD' THEN a.VL_INDICADOR ELSE NULL END) AS SPD,
		MAX(CASE WHEN a.COD_INDICADOR = 'BU' THEN a.VL_INDICADOR ELSE NULL END) AS BU,
		MAX(CASE WHEN a.COD_INDICADOR = 'MODALIDE' THEN a.VL_INDICADOR ELSE NULL END) AS MODALIDE,
		MAX(CASE WHEN a.COD_INDICADOR = 'STDEBITO' THEN a.VL_INDICADOR ELSE NULL END) AS STDEBITO,
		MAX(CASE WHEN a.COD_INDICADOR = 'STALUNO' THEN STA.SITUACAO_FINAL ELSE NULL END) AS STALUNO,
		MAX(CASE WHEN a.COD_INDICADOR = 'APROACAD' THEN a.VL_INDICADOR ELSE NULL END) AS APROACAD,
		MAX(CASE WHEN a.COD_INDICADOR = 'CURSO' THEN a.DESC_INDICADOR ELSE NULL END) AS CURSO,
		MAX(CASE WHEN b.CONTRATO_FIN IS NOT NULL THEN 'RENOVACAO' ELSE 'MENSALIDADE' END) AS PRODUTO,
		MAX(CASE WHEN a.COD_INDICADOR = 'ULTRENOV' THEN a.VL_INDICADOR ELSE NULL END) AS ULTRENOV,
		MAX(CASE WHEN a.COD_INDICADOR = 'LTCOMER' THEN a.VL_INDICADOR ELSE NULL END) AS LTCOMER
	FROM AUX_SYSOPENINDICADOR_YDUQS a
	LEFT JOIN AUX_SYSOPENSTATUSALUNO_YDUQS STA ON a.COD_INDICADOR = 'STALUNO' AND TRY_CAST(a.VL_INDICADOR AS INT) = STA.COD_SITUACAO
	LEFT JOIN AUX_SYSOPENINDICADOR_YDUQS b ON a.ID_CLIENTE = b.ID_CLIENTE AND a.COD_PRODUT = 1 AND b.COD_PRODUT = 2
	GROUP BY
		a.CONTRATO_FIN
) Y ON M.CONTRATO = Y.CONTRATO_FIN 
WHERE M.COD_CLI = 252 AND M.DATA = '20260112'


SELECT TOP 100 * FROM #BASE_YDUQS
WHERE CPF = '15566166784   ' AND DATA = '20260112'

SELECT COUNT(*) FROM #BASE_YDUQS WHERE ATRASO <= 0

SELECT 
    B.*,
    S.CUSTO AS CUSTO_SMS,
    R.CUSTO AS CUSTO_RCS,
    E.CUSTO AS CUSTO_EMAIL,
    W.CUSTO AS CUSTO_WHATS,
    S.TELEFONE AS TELEFONE_SMS,
    R.TELEFONE AS TELEFONE_RCS,
    W.TELEFONE AS TELEFONE_WHATS,
    E.EMAIL AS EMAIL
FROM #BASE_YDUQS B
LEFT JOIN [TRC-DC-BD2].PLANEJAMENTO.DBO.SMS S ON B.CPF = S.CPF AND CAST(S.DATA AS DATE) = '2026-01-12' AND S.ID_CAR = 95
LEFT JOIN [TRC-DC-BD2].PLANEJAMENTO.DBO.RCS R ON B.CPF = R.CPF AND CAST(R.DATA AS DATE) = '2026-01-12' AND R.ID_CAR = 95
LEFT JOIN [TRC-DC-BD2].PLANEJAMENTO.DBO.EMAIL E ON B.CPF = E.CPF AND CAST(E.DATA AS DATE) = '2026-01-12' AND E.ID_CAR = 95
LEFT JOIN [TRC-DC-BD2].PLANEJAMENTO.DBO.WHATS W ON B.CPF = W.CPF AND CAST(W.DATA AS DATE) = '2026-01-12' AND W.ID_CAR = 95
WHERE B.CPF = '3331762350    '


-- Para pagamento utilizar o arquivo de RPC - caso tenha uma ocorrencia de Promessa da operação dentro do mês considerar pagamento direto operação
-- Indicadores Principais

-- Resultados Financeiros

-- Valor total em atraso
-- Valor total recuperado
-- % de recuperação financeira
-- Ticket médio recuperado
-- Custo da campanha
-- Custo por real recuperado (ROI)



--  Performance de Conversão

-- Total de alunos acionados
-- Quantidade de alunos pagantes
-- Taxa de conversão em pagamento (%)
-- Tempo médio entre disparo e pagamento

-- Performance por Canal
-- (WhatsApp, RCS, SMS, Email)

-- Para cada canal, medir:
-- Volume disparado
-- Taxa de entrega
-- Taxa de leitura / abertura
-- Taxa de clique
-- Taxa de resposta
-- Conversão em pagamento
-- Valor recuperado por canal

-- Visões Necessárias no Relatório

-- Visão geral da campanha
-- Comparativo entre canais
-- Comparativo por período (dia / semana / mês)
-- Evolução diária da recuperação financeira
-- Ranking de canais mais eficientes
