# Cresol/src/database.py

COLUNAS_DISCAGENS = {
    'DATA':                 'data',
    'ID_DISCAGEM':          'id_discagem',
    'CONTRATO':             'contrato',
    'AGENTE':               'agente',
    'DDD':                  'ddd',
    'TELEFONE':             'telefone',
    'DATA_ENCERRAMENTO':    'data_encerramento',
    'CAMPANHA':             'campanha',
    'COD_SIP':              'cod_sip',
    'CLASS_RETORNO':        'class_retorno',
    'DESC_MOTIVO_ENCERR':   'desc_motivo_encerr',
    'COD_MOTIVO_ENCERR':    'cod_motivo_encerr',
    'OPERACAO':             'operacao',
    'ESTADO':               'estado',
    'ID_CAR':               'id_car',
    'ATRASO':               'atraso',
    'COD_CLI':              'cod_cli',
    'VALOR':                'valor',
    'PF_PJ':                'pf_pj',
    'PA':                   'pa',
    'CPF':                  'cpf',
    'nr_dia_util':          'nr_dia_util',
    'quartil':              'quartil',
    'dt_mes':               'dt_mes',
    'mes_abreviado':        'mes_abreviado',
}

COLUNAS_MAILING = {
    'DATA':      'data',
    'CONTRATO':  'contrato',
    'CPF':       'cpf',
    'ID_CAR':    'id_car',
    'ATRASO':    'atraso',
    'COD_CLI':   'cod_cli',
    'VALOR':     'valor',
    'PF_PJ':     'pf_pj',
    'PA':        'pa',
}

COLUNAS_ACIONAMENTOS = {
    'DATA_ACIONA':                  'data_aciona',
    'HORA':                         'hora',
    'CONTRATO_FIN':                 'contrato_fin',
    'CPF_DEV':                      'cpf_dev',
    'COD_ACIONA':                   'cod_aciona',
    'DESC_ACIONAMENTO':             'desc_acionamento',
    'COD_RECUP':                    'cod_recup',
    'NOME_RECUP':                   'nome_recup',
    'LOGIN_RECUP':                  'login_recup',
    'ULTGRUPO_RECUP':               'ultgrupo_recup',
    'VALORPRIN_FIN':                'valorprin_fin',
    'STATCONT_FIN':                 'statcont_fin',
    'DTDEVOL_FIN':                  'dtdevol_fin',
    'DTENTRADA_FIN':                'dtentrada_fin',
    'CLASSIFICACAO_ACIONAMENTO':    'classificacao_acionamento',
    'ACIONAMENTOS':                 'acionamentos',
    'CPC':                          'cpc',
    'CPCA':                         'cpca',
    'PROMESSA':                     'promessa',
    'DESCR':                        'descr',
    'CPF':                          'cpf',
    'ID_CAR':                       'id_car',
    'ATRASO':                       'atraso',
    'VALOR':                        'valor',
    'PF_PJ':                        'pf_pj',
    'PA':                           'pa',
    'COD_CLI':                      'cod_cli',
    'nr_dia_util':                  'nr_dia_util',
    'quartil':                      'quartil',
    'dt_mes':                       'dt_mes',
    'mes_abreviado':                'mes_abreviado',
}