-- 4260 Renner Manual
-- 4529 LOJAS RENNER MANUAL
-- Teste a conexão primeiro

DECLARE @DT_INI AS DATE = '2025-10-01' -- PRIMEIRO DIA DO MES
DECLARE @DT_FIM AS DATE = '2025-10-31' -- ULTIMO DIA DO MES
DECLARE @DT     AS DATE = '2025-10-08' -- PRIMEIRO DIA DESEJADO
DECLARE @DT2    AS DATE = '2025-10-08' -- ULTIMO DIA DESEJADO
DECLARE @DU INT = 1
DECLARE @SQL NVARCHAR(MAX);
DECLARE @TableName AS VARCHAR(50) = 'totalinfo_' + FORMAT(@DT_INI, 'yyyy_MM');

IF OBJECT_ID ('TEMPDB..##DISCAGENS') IS NOT NULL			DROP TABLE ##DISCAGENS

SET @SQL = '
SELECT *
INTO ##DISCAGENS
FROM OPENQUERY (EXPERT,''
	SELECT 
		A.Agente AS USUARIO,
		CASE
			WHEN A.OrigemChamada = ''''entrante'''' THEN COUNT(A.OrigemChamada)
		END RECEPTIVO,
		CASE
			WHEN A.OrigemChamada <> ''''entrante'''' THEN COUNT(A.OrigemChamada)
		END ATIVO,
		COUNT(*) TOTAL
	FROM ' + @TableName + ' a
	WHERE DATE(a.instante) = ''''' + CONVERT(VARCHAR(10), @DT2, 120) + '''''
	AND a.GrupoPrincipal IN (
		''''4522'''', -- LOJAS RENNER ATÉ 720 DIAS	
		''''4524'''', -- LOJAS RENNER - AGV
		''''4525'''', -- LOJAS RENNER ACIMA DE 721 DIAS	
		''''4526'''', -- LOJAS RENNER - CPC
		''''4527'''', -- LOJAS RENNER - RECADO
		''''4549'''', -- AGENTE VIRTUAL CPC RENNER	
		''''4528'''', -- LOJAS RENNER RECEPTIVO	
		''''4548'''', -- TRANSFERENCIA CPC RENNER
		''''4650'''',
		''''4543'''',
		''''4709'''',
		''''4770'''',	
		''''4529'''') -- LOJAS RENNER MANUAL
	GROUP BY A.Agente
'')';

EXEC sp_executesql @SQL;

SET @SQL = '
SELECT  
	''TRC'' AS COD_ASSESSORIA, 
	FORMAT(E.DATA, ''yyyyMM'') PERIODO, 
	FORMAT(E.DATA, ''dd/MM/yyyy'')+'' ''+CAST(E.HORA_LOGIN AS VARCHAR(8)) AS PRIMEIRO_LOGIN,
	FORMAT(E.DATA, ''dd/MM/yyyy'')+'' ''+CAST(E.HORA_LOGOUT AS VARCHAR(8)) AS ULTIMO_LOGOUT,
	E.USUARIO,
	''CLT'' REGIME,
	COALESCE(FORMAT(C.DTADMISSAO_RECUP, ''dd/MM/yyyy''),'''') DATA_ADMISSAO,
	''06:20:00'' CARGA_HORARIA,
	COALESCE(E.TEMPO_LOGADO,'''') TTL, 
	COALESCE(CONVERT(VARCHAR(8),
		DATEADD(SECOND, DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_LOGADO)
		- DATEDIFF(SECOND, ''00:00:00'', E.PAUSA)
		- DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_FALADO)
		- DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_TABULACAO)
	, ''00:00:00''), 108),'''') TTD,
	COALESCE(E.TTPNR,'''') TTPNR,
	COALESCE(E.TTPE,'''') TTPE,  
	COALESCE(E.TEMPO_TABULACAO,'''') TTT,  
	COALESCE(E.TEMPO_FALADO,'''') TTA,

	(CONVERT(VARCHAR(8),
         DATEADD(SECOND, (DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_LOGADO)
                 - DATEDIFF(SECOND, ''00:00:00'', E.PAUSA)
                 - DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_FALADO)
                 - DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_TABULACAO))
         /COALESCE(NULLIF(E.N_ATENDIDAS,0),1), ''00:00:00''), 108)) AS TMD,

	CONVERT(VARCHAR(8),
		DATEADD(SECOND, (DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_TABULACAO)
		/COALESCE(NULLIF(E.N_ATENDIDAS,0),1)), ''00:00:00''), 108) AS TMT,
	CONVERT(VARCHAR(8),
		DATEADD(SECOND, (DATEDIFF(SECOND, ''00:00:00'', E.TEMPO_FALADO)
		/COALESCE(NULLIF(E.N_ATENDIDAS,0),1)), ''00:00:00''), 108) AS TMA,
	COALESCE(D.ATIVO,0) ATENDIDAS_ATIVO,
	COALESCE(D.RECEPTIVO,0) ATENDIDAS_RECEPTIVO
FROM  
OPENQUERY (expert, ''
SELECT a.dia AS DATA,
	a.agente AS USUARIO,
	a.nome AS NOME,
	a.login AS HORA_LOGIN,
	a.logout AS HORA_LOGOUT,
	a.logado AS TEMPO_LOGADO,
	a.tempo_pausa_hora AS PAUSA,
	p.TTPNR,
	TIMEDIFF(a.tempo_pausa_hora,COALESCE(p.TTPNR,0)) TTPE,
	a.pausas_hora AS N_PAUSAS,
	a.atendidas AS N_ATENDIDAS,
	a.tempo_falado_hora AS TEMPO_FALADO,
	a.tempo_off_dia AS TEMPO_OCIOSIDADE,
	a.tempo_tabulacao_hora AS TEMPO_TABULACAO
FROM relatorio_agentes_hora a 
LEFT JOIN (SELECT
	SEC_TO_TIME(SUM(TIME_TO_SEC(TIMEDIFF(DSC_FINAL, DSC_INICIO)))) AS TTPNR,
	DSC_AGENTE,
	DATE(DAT_OCORRENCIA) AS DATA
	FROM tb_relatorio_pausa
	WHERE (DSC_PAUSA LIKE ''''%PAUSA%EXPERT%'''' OR DSC_PAUSA LIKE ''''%10%'''' OR DSC_PAUSA LIKE ''''%20%'''')
	GROUP BY DSC_AGENTE, DATE(DAT_OCORRENCIA)
	) p ON a.agente = p.dsc_agente AND a.dia = p.data
WHERE 
	a.dia = ''''' + CONVERT(VARCHAR(10), @DT2, 120) + '''''
	AND a.grupoprincipal in (''''4543'''', ''''4709'''', ''''4770'''')
'') E
LEFT JOIN CAD_RECUP C ON E.USUARIO = C.CODDISCA_RECUP COLLATE SQL_Latin1_General_CP1_CI_AS AND C.ULTGRUPO_RECUP = ''RENNER''
LEFT JOIN ##DISCAGENS D ON E.USUARIO = D.USUARIO
';

EXEC sp_executesql @SQL;